#!/usr/bin/env bash
#Why you no love me project

echo $$ >> /var/run/myscript.pid
while :
do
echo "To infinity and beyond";
sleep 2;
trap "echo 'Y U no love me?!'" SIGINT;
trap "echo 'I hate the kill command'; rm -f /var/run/myscript.pid; exit" SIGTERM; SIGQUIT;
done
