#!/usr/bin/env bash
#Bash script that displays: To infinity and beyond indefinitely With a sleep 2 in between each iteration
file="I am invincible!!!"
while :
do
echo "To infinity and beyond";
sleep 2;
trap 'echo $file' SIGTERM;
done
